name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ruby_unit_tests:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - run: gem install bundler -v 2.1.4

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: v1-bundle-cache-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v1-bundle-cache-

      - run: bundle config set path 'vendor/bundle'
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rspec spec
