name: Linters

on: [pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.x'

      - run: gem install rubocop:0.79.0 rubocop-rails:2.4.1 rubocop-rspec:1.33.0

      - name: Install reviewdog
        run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s

      - name: Run RuboCop
        run: |
          diff_sha=$(git rev-parse "origin/${{ github.base_ref }}")
          rubocop app lib spec | ./bin/reviewdog -f=rubocop -diff="git diff $diff_sha" -reporter=github-pr-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
